default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubygems_development

test:
  <<: *default
  database: rubygems_test

production:
  <<: *default
  database: rubygems_production
  username: rubygems
  password: <%= ENV["RUBYGEMS_DATABASE_PASSWORD"] %>
